name: Test
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
    tags-ignore:
      - '*'

env:
  PROJECT_NAME: <PROJECT_NAME>
  TEST_PROJECT_NAME: <PROJECT_NAME>.Tests

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os.runner }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: Windows, runner: windows-latest, runtime: win-x64 }
          - { name: MacOS, runner: macos-latest, runtime: osx-x64 }
          - { name: Linux, runner: ubuntu-latest, runtime: linux-x64 }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install Optional Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev \
            libsdl2-dev \
            llvm-dev \
            xvfb \
            xauth

      - name: Setup Xvfb
        run: |
          mkdir .staging
          wget -O Xvfb.service https://gist.githubusercontent.com/ypandit/f4fe751bcbf3ee6a32ca/raw/f2f3a955e430e1f574c985cec0947d55496066d3/Xvfb.service
          sudo mv Xvfb.service /etc/systemd/system/Xvfb.service
          sudo systemctl daemon-reload
          sudo systemctl start Xvfb
          sudo systemctl status Xvfb

      - name: Build <PROJECT>
        run: dotnet build ${{ env.PROJECT_NAME }} -r ${{ matrix.os.runtime }} --self-contained

      - name: Test <PROJECT>
        run: dotnet test ${{ env.TEST_PROJECT_NAME }} -r ${{ matrix.os.runtime }} --logger "trx;LogFileName=TestResults-${{ matrix.os.name }}.trx"

      - name: Upload test artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: TestResults-${{ matrix.os.name }}
          path: ${{ env.TEST_PROJECT_NAME }}/TestResults/*.trx
