name: Test
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Test
        run: dotnet test ${{ inputs.path }} --logger "trx;LogFileName=TestResults-${{ inputs.name }}.trx"

      - name: Upload Results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: TestResults-${{ inputs.name }}
          path: ${{ github.workspace }}/${{ inputs.path }}/TestResults/TestResults-${{ inputs.name }}.trx

